### ISSUE TITLE
How get events

### ISSUE THREAD

**Issue by chinyaev** [richardwilkes/cef#3]
Hi @richardwilkes!

How I can bind events? Example onLoadEnd or onAddressChange

**Comment by chuprik** [comment]
any news here???

**Comment by richardwilkes** [comment]
This repo contains bindings for the CEF API for Go. Info on how to use them is on the CEF site. If there is something specific that you've found wrong with the bindings, I'm happy to take a look -- post an example of what failed and describe what you expected.

**Comment by Chinyaev** [comment]
> This repo contains bindings for the CEF API for Go. Info on how to use them is on the CEF site. If there is something specific that you've found wrong with the bindings, I'm happy to take a look -- post an example of what failed and describe what you expected.

I mean how register method in handler?
Example In cefpython I can do so - `browser.SetClientHandler(LoadHandler())`
```
class LoadHandler(object):
    def OnLoadingStateChange(self, browser, is_loading, **_):
            js_print(browser, "Python", "OnLoadingStateChange", "Loading is complete")
```

In cef4Delphi I can do so - `TempChromium.OnLoadingStateChange := Chromium_LoadingStateChange;`
```
procedure Chromium_LoadingStateChange(Sender: TObject; const browser: ICefBrowser; isLoading, canGoBack, canGoForward: Boolean);
begin
//code
end;
```
Maybe you will give an example of how to register a cef function in your library? Sorry If my question is stupid, I have little experience in Go and Cef.

**Comment by richardwilkes** [comment]
If you'd like to see an example of actual use of the API, the readme for the repo contains links to a working web app example.

For the above, you'd need to create a new client view cef.NewClient(), passing in your client proxy that implemented the handlers you wanted to override.

**Comment by Chinyaev** [comment]
Thank you for responses. Your sample app does not contains example works handlers.

I created function
`func onAddressChange(browser *cef.Browser, frame *cef.Frame, url string) {
	w.ExecuteJavaScript("alert();", "", 0)
}`

And I try to set
```
	var t cef.ClientProxy
	var d = t.GetDisplayHandler(nil)
	d.OnAddressChange = onAddressChange //error cannot assign to d.OnAddressChange(undefined)
	var c = cef.NewClient(t)
```

I can't understand how handlers work, help me please with a small example

**Comment by habokuntes** [comment]
@Chinyaev have a look at the client.go within the webapp project. This project here contains only the native bindings, because otherwise it would be always overwritten with a new update. I do not have the time right now to look deeper into the code, but if you look into the webapp project, then you will see that inside client.go the KeyboardHandler is already defined there. 

```
type client struct {
	keyboardHandler *cef.KeyboardHandler
}

func newClient() *cef.Client {
	c := &client{}
	c.keyboardHandler = cef.NewKeyboardHandler(c)
	c.keyboardHandler.Base().AddRef()
	return cef.NewClient(c)
}

func (c *client) GetKeyboardHandler(self *cef.Client) *cef.KeyboardHandler {
	c.keyboardHandler.Base().AddRef()
	return c.keyboardHandler
}
```

If you want use the DisplayHandler, then I guess you need first to define it on your own + define the
*cef.DisplayHandler as type into your client struct, so that you can use the callback within your webapp project.

After you get it work add also some unit tests, so that you are with a newer cef version on the safe side. Sorry that I cannot give you a full example, but I hope that helps. 

@richardwilkes thanks for your great work. looks very promising and clean. Unfortunately I had to decide 4 weeks ago, which cef implementation I will use for my first release and did not saw your implementation, But I hope I will find the time to rewrite the code to golang with the next release and maybe find the time for a linux wrapper.
