### ISSUE TITLE
Javascript Function

### ISSUE THREAD

**Issue by Gurkengewuerz** [richardwilkes/cef#9]
I have spent the last few days looking at some WebView alternatives. As it looks like the Chrome Embedded Framework is my way to go.
I first tried to write the bindings myself, but apparently yours @richardwilkes are pretty good and kept up-to-date.
My most important question: Is there a way to create your own javascript functions? Did I miss something?

In the CAPI of CEF the function is `cef_v8value_create_function` to create a V8Handler.

Thanks for your help.

**Comment by richardwilkes** [comment]
I think you're looking fro this: `V8valueCreateFunction()`

I created these bindings for a project nearly 2 years ago, but that project has since decided to move away from CEF for various reasons (mostly not related to CEF). Since that occurred, I've not put much effort into maintaining this repo. In particular, I stopped updating it to the latest CEF library when I discovered that tighter restrictions in macOS had forced the CEF library to require some features be enabled that I had not taken the time to figure out how to support (I believe these were around runtime hardening and the sandbox, but I don't recall for certain).

Anyway, glad to hear that others still find it useful, but you should be aware that I'm unlikely to update these bindings beyond where they stand today. :-(

**Comment by Gurkengewuerz** [comment]
Looks like it. Thank you! :)
I'm gonna go play with the library. Unfortunately the rest of the libraries out there are not what I am looking for. WebView has very bad Windows 7 support and with EdgeHTML the rendering engine is quite limited (e.g. scrollbar can't be changed). Ultralight is so far the best alternative but it lacks too many functions and you can't help much because it is closed source.

If I run into problems, I might be able to provide a PR for patches. 

Are you currently using anything else or are WebViews no longer interesting for you?

**Comment by richardwilkes** [comment]
That particular project decided to not have a local application at all and just be hosted in the cloud, so a web browser was all that was needed in the end.
